(()=>{"use strict";
const $=x=>document.getElementById(x);
const names=["北方","東北方","東方","東南方","南方","西南方","西方","西北方"];
const screenNames=["上方","右上","右方","右下","下方","左下","左方","左上"];
const v=[{x:0,z:-1},{x:1,z:-1},{x:1,z:0},{x:1,z:1},{x:0,z:1},{x:-1,z:1},{x:-1,z:0},{x:-1,z:-1}];
const THEMES=[
 {name:"陽光公園",badge:"🌤️",sky:0xbfeeff,ground:0x8dd783,path:0xf0d6a5,roof:0xf26f5d,weather:"none",accent:0xffdc7a},
 {name:"雨天小鎮",badge:"🌧️",sky:0xa9cce0,ground:0x72b889,path:0xe1d6b4,roof:0x4f9ee7,weather:"rain",accent:0x7fd0ff},
 {name:"雪花廣場",badge:"❄️",sky:0xddefff,ground:0xd8eef8,path:0xeef3f6,roof:0xa17de6,weather:"snow",accent:0xffffff},
 {name:"森林秘境",badge:"🌲",sky:0xc7efd6,ground:0x78c071,path:0xd9c38e,roof:0xe68747,weather:"leaves",accent:0x93ff93},
 {name:"彩虹花園",badge:"🌈",sky:0xd7e8ff,ground:0x98d87e,path:0xead4bc,roof:0xff8c8c,weather:"sparkle",accent:0xff8ee8}
];
let sc,cam,ren,pl,clock=new THREE.Clock(),g=[],parts=[],world=[],wx=[];
let level=1,score=0,streak=0,north=0,last=-1,target=0,busy=0,move=null,themeIndex=0;
const btn=[...document.querySelectorAll('.dir')],R=5.35,S=4.25,TOTAL=12;
function M(c,r=.75,e=0,ei=.0){return new THREE.MeshStandardMaterial({color:c,roughness:r,emissive:e?c:0x000000,emissiveIntensity:ei})}
function B(w,h,d,c,r=.75,e=0,ei=.0){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),M(c,r,e,ei));m.castShadow=m.receiveShadow=1;return m}
function C(a,b,h,c,r=.75,e=0,ei=.0){let m=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,18),M(c,r,e,ei));m.castShadow=m.receiveShadow=1;return m}
function sphere(r,c,e=0,ei=.0){let m=new THREE.Mesh(new THREE.SphereGeometry(r,18,14),M(c,.55,e,ei));m.castShadow=m.receiveShadow=1;return m}
function currentTheme(){return THEMES[themeIndex]}
function camera(){let a=innerWidth/innerHeight;cam.aspect=a;cam.fov=a<.78?46:a<1.15?44:41;cam.position.set(0,a<.78?22.5:a<1.15?19.5:17,a<.78?18.5:a<1.15?16.2:14.2);cam.lookAt(0,.45,0);cam.updateProjectionMatrix()}
function init(){sc=new THREE.Scene;ren=new THREE.WebGLRenderer({antialias:1,alpha:0});ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.setSize(innerWidth,innerHeight);ren.shadowMap.enabled=1;$('game').appendChild(ren.domElement);cam=new THREE.PerspectiveCamera(43,1,.1,100);camera();sc.add(new THREE.HemisphereLight(0xffffff,0x5e7f61,2.4));let sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-8,15,9);sun.castShadow=1;sun.shadow.mapSize.set(1024,1024);sc.add(sun);pl=player();build();sc.add(pl);addEventListener('resize',()=>{ren.setSize(innerWidth,innerHeight);camera()});newRound();loop()}
function player(){let q=new THREE.Group,b=C(.35,.45,.92,0x2d79c8),cape=C(.24,.3,.52,0x1f5ea7);b.position.y=.9;cape.position.set(0,.92,-.08);q.add(b,cape);let h=sphere(.32,0xffd1aa);h.position.y=1.58;q.add(h);let hair=new THREE.Mesh(new THREE.SphereGeometry(.335,18,14,0,Math.PI*2,0,Math.PI/2),M(0x24384b,.85));hair.position.y=1.67;q.add(hair);q.position.y=.2;return q}
function clearWeather(){wx.forEach(o=>sc.remove(o));wx=[]}
function addWeather(){clearWeather();let th=currentTheme();if(th.weather==="none")return;for(let i=0;i<80;i++){
 let m;if(th.weather==="rain")m=B(.03,.55,.03,0x9be5ff,.2,1,.4);else if(th.weather==="snow")m=sphere(.06+Math.random()*.05,0xffffff,1,.3);else if(th.weather==="leaves")m=B(.08,.02,.12,Math.random()>.5?0xe4b54d:0xc97b33,.5);else m=sphere(.05+Math.random()*.03,[0xff8ee8,0x8effff,0xfff38e][i%3],1,.35);
 m.position.set((Math.random()-.5)*16,4+Math.random()*10,(Math.random()-.5)*16);m.userData={vx:(Math.random()-.5)*(th.weather==="rain"?.1:.5),vy:th.weather==="rain"?-(.18+Math.random()*.18):-(.03+Math.random()*.08),vz:(Math.random()-.5)*(th.weather==="snow"?.08:.18),spin:(Math.random()-.5)*.08};sc.add(m);wx.push(m)
 }}
function build(){let t=currentTheme();sc.background=new THREE.Color(t.sky);g=[];world=[];let base=B(16.8,.6,16.8,t.ground);base.position.y=-.34;sc.add(base);world.push(base);for(let o of [[14.8,.08,3],[3,.08,14.8]]){let p=B(o[0],o[1],o[2],t.path);p.position.y=.02;sc.add(p);world.push(p)}let fountain=C(1.05,1.22,.34,0xe5f4fa,.35);fountain.position.y=.17;let water=C(.8,.8,.12,0x59c0ed,.2,1,.25);water.position.y=.39;sc.add(fountain,water);world.push(fountain,water);
 for(let i=0;i<8;i++){let a=i*Math.PI/4,x=Math.sin(a)*R,z=-Math.cos(a)*R,q=new THREE.Group,p=C(.9,1,.18,0xffffff);p.position.y=.1;q.add(p);[-.55,.55].forEach(k=>{let s=B(.2,1.9,.2,0xf7fafc);s.position.set(k,1.02,0);q.add(s)});let top=B(1.35,.23,.26,t.roof,.5);top.position.y=1.94;q.add(top);let ringCol=[0xff7065,0xffb34d,0x5fb9ee,0x8f79e9,0x55c88b,0xf18ac0,0x53d0c2,0xffd35c][i];let ring=new THREE.Mesh(new THREE.TorusGeometry(.54,.085,10,32),new THREE.MeshStandardMaterial({color:ringCol,emissive:ringCol,emissiveIntensity:1.2}));ring.position.y=1.1;q.add(ring);let glow=sphere(.12,t.accent,1,.45);glow.position.y=.75;q.add(glow);q.position.set(x,0,z);q.rotation.y=-a;q.userData={ring,glow,stand:new THREE.Vector3(Math.sin(a)*S,.2,-Math.cos(a)*S)};sc.add(q);g.push(q)}
 for(let i=0;i<8;i++){let a=i*Math.PI/4+Math.PI/8,x=Math.cos(a)*6.8,z=Math.sin(a)*6.8,tr=C(.12,.17,.82,0x7b5339);tr.position.set(x,.41,z);let cr=C(.46,.68,1.08,i%2?0x4fae64:0x67bd70,.7);cr.position.set(x,1.3,z);sc.add(tr,cr);world.push(tr,cr)}
 if(t.name==="森林秘境"){for(let i=0;i<6;i++){let x=(Math.random()-.5)*9,z=(Math.random()-.5)*9;if(Math.abs(x)<2||Math.abs(z)<2)continue;let mush=C(.14,.18,.18,0xf9e4d7);mush.position.set(x,.1,z);let cap=C(.28,.05,.18,0xd45a4d);cap.position.set(x,.32,z);sc.add(mush,cap);world.push(mush,cap)}}
 if(t.name==="彩虹花園"){for(let i=0;i<6;i++){let f=sphere(.09,[0xff9fc1,0xffe088,0x89e6a8,0x8fd8ff,0xd3a2ff,0xffa7e4][i],1,.25);f.position.set((Math.random()-.5)*8,.45,(Math.random()-.5)*8);sc.add(f);world.push(f)}}
 addWeather();$('sceneBanner').textContent=`${t.badge} ${t.name}`
}
function rebuild(){g.forEach(x=>sc.remove(x));world.forEach(x=>sc.remove(x));clearWeather();g=[];world=[];build();sc.add(pl)}
function roundCompass(){do north=Math.floor(Math.random()*8);while(north===last);last=north;let d=north*45;$('needle').style.transform=`rotate(${d}deg)`;let c=$('compass').clientWidth/2,r=c*.82,a=(d-90)*Math.PI/180;$('n').style.left=c+Math.cos(a)*r+'px';$('n').style.top=c+Math.sin(a)*r+'px';labels()}
function labels(){$('big').querySelectorAll('.lab').forEach(x=>x.remove());let s=$('big').clientWidth||400,c=s/2,r=s*.39;for(let i=0;i<8;i++){let j=(north+i)%8,a=(j*45-90)*Math.PI/180,e=document.createElement('div');e.className='lab'+(i?'':' north');e.textContent=names[i];e.style.left=c+Math.cos(a)*r+'px';e.style.top=c+Math.sin(a)*r+'px';$('big').appendChild(e)}}
function newRound(){busy=0;pl.position.set(0,.2,0);pl.rotation.y=0;roundCompass();target=Math.floor(Math.random()*8);$('lv').textContent=`第${level}關`;$('score').textContent=`分數${score}`;$('streak').textContent=`連勝${streak}`;$('task').innerHTML=`請找出 <b>${names[target]}</b> 的門`;btn.forEach(x=>x.disabled=0)}
function choose(i){if(busy)return;busy=1;btn.forEach(x=>x.disabled=1);let end=g[i].userData.stand.clone(),start=pl.position.clone(),f=g[i].position.clone().sub(end);pl.rotation.y=Math.atan2(f.x,f.z);move={start,end,t:performance.now(),dur:900,done:()=>judge(i)}}
function judge(i){move=null;if(i===(north+target)%8){streak++;score+=100+Math.min(streak,5)*10;$('score').textContent=`分數${score}`;$('streak').textContent=`連勝${streak}`;portalBurst(g[i].position);toast(`方向正確！\n到達${names[target]}`,'good');setTimeout(nextScene,1050)}else{streak=0;$('streak').textContent=`連勝${streak}`;toast(`方向不正確\n你選擇了${screenNames[i]}`,'bad');setTimeout(()=>{let s=pl.position.clone(),e=new THREE.Vector3(0,.2,0);move={start:s,end:e,t:performance.now(),dur:850,done:()=>{busy=0;btn.forEach(x=>x.disabled=0)}}},850)}}
function toast(txt,cls){let t=$('toast');t.innerHTML=txt.replace(/\n/g,'<br>');t.className='show '+cls;setTimeout(()=>t.className='',1350)}
function portalBurst(p){for(let i=0;i<68;i++){let col=[0xffffff,currentTheme().accent,0x63dfff,0xffd36d][i%4],m=sphere(.05+Math.random()*.05,col,1,.35);m.position.copy(p).add(new THREE.Vector3(0,.9,0));sc.add(m);parts.push({m,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*4.8,(Math.random()-.5)*4),life:1.15})}}
function nextScene(){if(level>=TOTAL){$('tt').textContent='🏆 完成所有關卡！';$('ts').textContent='你已經完成整個八方向冒險！';showTransition();setTimeout(()=>{$('tt').textContent='恭喜完成！';busy=1},50);return}level++;themeIndex=level===1?0:Math.floor(Math.random()*THEMES.length);$('tt').textContent='過關成功！';$('ts').textContent=`進入第${level}關：${THEMES[themeIndex].name}`;showTransition();setTimeout(()=>{rebuild();newRound()},620);setTimeout(()=>{busy=0},1600)}
function showTransition(){let tr=$('transition');clearTimeout(tr.hideTimer);tr.querySelectorAll('.spark').forEach(x=>x.remove());for(let i=0;i<26;i++){let s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=60+Math.random()*35+'%';s.style.animationDelay=Math.random()*1.1+'s';tr.appendChild(s)}tr.classList.remove('show');void tr.offsetWidth;tr.classList.add('show');tr.hideTimer=setTimeout(()=>{tr.classList.remove('show');tr.querySelectorAll('.spark').forEach(x=>x.remove())},1650)}
function animateWeather(t){let k=currentTheme().weather;for(let i=0;i<wx.length;i++){let m=wx[i];m.position.x+=m.userData.vx;m.position.y+=m.userData.vy;m.position.z+=m.userData.vz;if(k==='leaves')m.rotation.z+=m.userData.spin;if(k==='sparkle')m.material.emissiveIntensity=.2+Math.sin(t*3+i)*.35;if(m.position.y<-0.2){m.position.y=8+Math.random()*6;m.position.x=(Math.random()-.5)*16;m.position.z=(Math.random()-.5)*16}}}
function loop(){requestAnimationFrame(loop);let now=performance.now(),dt=Math.min(clock.getDelta(),.035),tm=now*.001;if(move){let p=Math.min(1,(now-move.t)/move.dur),e=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;pl.position.lerpVectors(move.start,move.end,e);pl.position.y=.2+Math.abs(Math.sin(tm*10))*.08;if(p>=1){let d=move.done;move=null;d()}}else pl.position.y=.2+Math.sin(tm*2.1)*.02;g.forEach((q,i)=>{q.userData.ring.rotation.z=tm*.45*(i%2?1:-1);q.userData.ring.position.y=1.1+Math.sin(tm*2+i)*.06;q.userData.glow.material.emissiveIntensity=.25+Math.sin(tm*3+i)*.2});animateWeather(tm);for(let i=parts.length-1;i>=0;i--){let p=parts[i];p.life-=dt;p.v.y-=4*dt;p.m.position.addScaledVector(p.v,dt);p.m.material.opacity=Math.max(0,p.life);if(p.life<=0){sc.remove(p.m);parts.splice(i,1)}}ren.render(sc,cam)}
btn.forEach(x=>x.onclick=()=>choose(+x.dataset.i));$('hint').onclick=()=>{$('modal').classList.add('open');setTimeout(labels,0)};$('close').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};init();
})();